insert into manufacturers (id, name) values (1, 'Vallejo Acrylics');

-- Game Color
insert into product_lines (id, name, manufacturer_id) values (1, 'Game Color', 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dead White', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Bone White', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Pale Flesh', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Rosy Flesh', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Athena Skin','ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Elf Skin Tone', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Barbarian SKin', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Toxic Yellow', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Moon Yellow', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sun Yellow', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Gold Yellow', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Scrofulous Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Orange Fire', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Hot Orange', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Bloody Red', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Scarlet Red', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Gory Red', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Nocturnal Red', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Squid Pink', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Warlord Purple', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Lustful Purple', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Alien Purple', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Hexed Lichen', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Royal Purple', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Midnight Purple', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Elfic Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Ultramarine Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Night Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sunrise Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Electric Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Magic Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Imperial Blue', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Turquoise', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Abyssal Turquoise', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Ghost Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Foul Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Jade Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Scurvy Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Bile Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Scorpy Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Goblin Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sick Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Angel Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dark Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dead Flesh', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Camouflage Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dirty Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Cayman Green', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Khaki', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Desert Yellow', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Earth', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Bronze Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Plague Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Leather Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Beasty Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Parasite Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Gorgone Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dark Fleshtone', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Charred Brown', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Wolf Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sombre Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Warm Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Stonewall Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Neutral Grey', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Charcoal', 'ff0000', 1, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Black', '000000', 1, 1);

-- Game Color Wash
insert into product_lines (id, name, manufacturer_id) values (2, 'Game Color Wash', 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Yellow', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Flesh', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Red', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Violet', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Blue', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Umber', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sepia', 'ff0000', 2, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Black', 'ff0000', 2, 1);

-- Game Color Fluo
insert into product_lines (id, name, manufacturer_id) values (3, 'Game Color Fluo', 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Yellow', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Orange', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Red', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Magenta', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Violet', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Blue', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Green', 'ff0000', 3, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Fluo Cold Green', 'ff0000', 3, 1);

-- Game Color Ink
insert into product_lines (id, name, manufacturer_id) values (4, 'Game Color Ink', 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('White', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Skin', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Yellow', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Red', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Magenta', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Violet', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Blue', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Dark Turquoise', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Green', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Black Green', 'ff0000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Sepia', '000000', 4, 1);
insert into paints (name, color, product_line_id, manufacturer_id) values ('Black', '000000', 4, 1);